### ISSUE TITLE
How is crib.showDetails working?

### ISSUE THREAD

**Issue by MHoonCIC** [chenkie/ng2-cribs#1]
Can't figure out how line *ngIf="!crib.showDetails is working in the crib-card.component.html. 'showDetails' is not a property in the crib interface nor do I see any definition for it.

**Comment by chenkie** [comment]
Good question! In this case, since this is just a boolean we're checking on, we don't actually need to define it anywhere first. BUT it would indeed be better/more clear if it were defined in the component class.

What's happening is that when the page loads, `showDetails` will be `undefined`. Since this is a falsey value, it will work just the same is it would if it were actually initially set to `false`. Then when it is later set to `true`, it essentially gets defined at that moment.

**Comment by MHoonCIC** [comment]
Thank you!
